export interface DLCSettings {
  period?: number; 
  pocLookback?: number;
  numProfiles?: number; 
  pocColor?: string;
  vahColor?: string;
  valColor?: string;
  numBins?: number;
  vaPercentage?: number;
}

export interface NWESettings {
  enabled?: boolean;
  bandwidth?: number;
  multiplier?: number;
  source?: 'open' | 'high' | 'low' | 'close';
  repaint?: boolean;
  upColor?: string;
  downColor?: string;
}

export interface ClusterSettings {
  source?: 'delta' | 'volume'; 
  minVolumeThresholdMultiplier?: number;
  deltaThreshold?: number;
  lookbackPeriod?: number;
  confirmationBars?: number; 
  buyColor?: string;   
  sellColor?: string;  
}

export interface RiskManagementSettings {
  atrPeriod?: number; 
  stopLossMultiplier?: number; 
  takeProfitMultiplier?: number; 
  useTrailingStop?: boolean; 
  trailingStopOffsetMultiplier?: number;
  trailingStopStepMultiplier?: number;
  maxTradesPerDay?: number; 
  positionSizePercentage?: number; 
  maxRiskPerTradePercentage?: number; 
}

export interface StrategyParameters {
  dlc?: DLCSettings;
  nwe?: NWESettings;
  clusters?: ClusterSettings;
  risk?: RiskManagementSettings;
}

// New Interfaces for Backtesting

export interface BacktestRunParameters {
  pairSymbol: string;
  timeframe: string;
  startDate: string; // ISO string date
  endDate: string;   // ISO string date
  initialCapital: number;
  strategyParameters: StrategyParameters; 
}

export interface Trade {
  id?: string; // uuid or similar, generated by backend
  entryTimestamp: number;
  entryPrice: number;
  exitTimestamp?: number;
  exitPrice?: number;
  direction: 'long' | 'short';
  size: number;
  pnl?: number;
  stopLoss?: number;
  takeProfit?: number;
  entryReason?: string;
  exitReason?: string;
  // Optional fields from backend calculation if available
  commission?: number;
  slippage?: number;
  duration?: number; // in milliseconds or seconds
  profitPercentage?: number;
  riskRewardRatio?: number;
}

export interface BacktestMetrics {
  // Basic Metrics
  totalPnl: number;
  totalTrades: number;
  winningTrades: number;
  losingTrades: number;
  winRate: number; // e.g., 0.55 for 55%
  profitFactor: number;
  maxDrawdown: number; // e.g., 0.10 for 10%
  
  // Additional PnL Metrics
  grossProfit: number;
  grossLoss: number;
  averageTradePnl: number;
  avgWinningTrade?: number;
  avgLosingTrade?: number;
  expectancy?: number; // (Win Rate * Avg Win) - (Loss Rate * Avg Loss)
  
  // Duration Metrics
  totalTimeInMarket?: number; // in ms or suitable unit
  avgTradeDuration?: number;

  // Risk & Other
  sharpeRatio?: number; // (needs risk-free rate)
  sortinoRatio?: number; // (needs risk-free rate & downside deviation)
  calmarRatio?: number; // (annualized RoR / max drawdown)
  
  // Equity related
  initialCapital: number;
  finalCapital: number;
  equityCurve: { timestamp: number; capital: number }[];
  
  [key: string]: any; // To allow for additional dynamic metrics passed from backend
}

export interface BacktestResult {
  jobId?: string; // If jobs are managed asynchronously
  status?: 'queued' | 'running' | 'completed' | 'failed';
  message?: string; // For status updates or errors
  metrics: BacktestMetrics;
  trades: Trade[];
  logs?: string[]; // Optional logs from the backtest run
  configUsed?: BacktestRunParameters; // To know what params generated this result
} 